apiVersion: apps/v1
kind: Deployment
metadata:
  name : adminer-deployment
  labels:
   name : adminer
   owner: limwaer
   env  : dotenv
   app  : bot-app-deployment
spec:
  selector:
    matchLabels:
      project: bot
  template:
    metadata:
      labels:
        project: bot
  spec:
    containers:
      - name: adminer
        image: adminer
        ports:
          - containerPort: 8080
    restartPolicy: Always
