apiVersion: v1
kind: Service
metadata:
  name : adminer-service
  labels:
   name : adminer
   owner: limwaer
   env  : dotenv
   app  : bot-app-deployment
spec:
  selector:
    project: bot
  ports:
    - name      : adminer-listener
      protocol  : TCP
      port      : 8080
      targetPort: 8080
  type: LoadBalancer


