apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: bot
    spec:
      containers:
        - env:
            - name: ADMIN_ID
              valueFrom:
                secretKeyRef:
                  key: ADMIN_ID
                  name: pg-secret
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: PGHOST
                  name: pg-secret
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  key: PG_PASS
                  name: pg-secret
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: PG_USER
                  name: pg-secret
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: pg-secret
          image: limwaer/great-tester-bot:2.0
          name: bot
          ports:
            - containerPort: 7777
          resources: {}
          workingDir: /app
      restartPolicy: Always
status: {}
