version: '3.8'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - 5432:5432
#    networks:
#      - bridge

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#    networks:
#      - bridge

  bot:
    image: limwaer/great-tester-bot:2.0
    container_name: bot
    restart: always
    ports:
      - 7777:7777
    depends_on:
      - db
    links:
      - "db:database"
    env_file:
      - .env
    environment:
      PGHOST: 192.168.32.2
    working_dir: /app
#    volumes:
#    - ./:/app/
#    networks:
#      - bridge


#networks:
#  bridge:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.32.0/20
#          gateway: 192.168.32.1
#          aux_addresses:
#            db: 192.168.32.2
#            adminer: 192.168.32.3
#            bot: 192.168.32.4